# Generated by Django 5.1.1 on 2024-09-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_machines_rename_enterprise_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectors',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.company'),
        ),
    ]
