# Generated by Django 5.1.1 on 2024-09-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0005_macid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
