# Generated by Django 5.1.1 on 2024-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0006_alter_machines_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='macid',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
