# Generated by Django 5.1.1 on 2024-09-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0007_machines_status_macid_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='macid',
            old_name='status',
            new_name='active',
        ),
    ]
