# Generated by Django 5.1.1 on 2024-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0008_rename_status_machines_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
