# Generated by Django 4.1.13 on 2024-09-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0009_alter_machines_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companyes'},
        ),
        migrations.AlterModelOptions(
            name='machines',
            options={'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
        migrations.AlterModelOptions(
            name='sectors',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
    ]
