# Generated by Django 4.1.13 on 2024-10-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0010_alter_company_options_alter_machines_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='macid',
            unique_together={('mac_id', 'machine')},
        ),
    ]
