# Generated by Django 4.1.13 on 2024-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0011_alter_macid_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_inicio_almoco', models.TimeField()),
                ('hora_fim_almoco', models.TimeField()),
            ],
        ),
    ]
