# Generated by Django 4.2.23 on 2025-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0012_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='macid',
            name='ip_adress',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
