# Generated by Django 4.2.23 on 2025-09-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0013_macid_ip_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_station', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule.machines')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.sectors')),
            ],
        ),
        migrations.AddField(
            model_name='macid',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rule.workstation'),
        ),
    ]
