# Generated by Django 4.2.23 on 2025-09-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0014_workstation_macid_workstation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstation',
            options={'verbose_name': 'Posto de Trabalho', 'verbose_name_plural': 'Postos de Trabalho'},
        ),
        migrations.RemoveField(
            model_name='machines',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='sectors',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workstation',
            name='code_station',
        ),
        migrations.RemoveField(
            model_name='workstation',
            name='machine',
        ),
        migrations.AddField(
            model_name='machines',
            name='turnowork',
            field=models.ManyToManyField(blank=True, to='rule.turno'),
        ),
        migrations.AddField(
            model_name='machines',
            name='workStation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.workstation'),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_fim_almoco',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_inicio_almoco',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.company')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.AddField(
            model_name='sectors',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.group'),
        ),
    ]
