# Generated by Django 4.2.23 on 2025-07-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cad_item', '0024_alter_familyprod_options'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_number', models.CharField(max_length=50, unique=True)),
                ('pedido_cliente', models.CharField(blank=True, default='-', max_length=50, null=True)),
                ('cargo_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('lacre_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('status', models.CharField(choices=[('OPE', 'Aberto'), ('LOD', 'Carregando'), ('CAN', 'Cancelado'), ('FIN', 'Concluído')], default='OPE', max_length=3, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cad_item.finish')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cad_item.item')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.pedidos')),
            ],
            options={
                'verbose_name': 'Item Proforma',
                'verbose_name_plural': 'Itens Proforma',
            },
        ),
    ]
