# Generated by Django 4.2.30 on 2026-04-08 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("_itens", "0001_initial"),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pedido_number", models.CharField(max_length=50, unique=True)),
                (
                    "pedido_cliente",
                    models.CharField(
                        blank=True, default="--", max_length=50, null=True
                    ),
                ),
                (
                    "cargo_number",
                    models.CharField(
                        blank=True, default="--", max_length=50, null=True
                    ),
                ),
                (
                    "lacre_number",
                    models.CharField(
                        blank=True, default="--", max_length=50, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPE", "Aberto"),
                            ("LOD", "Carregando"),
                            ("CAN", "Cancelado"),
                            ("FIN", "Concluído"),
                        ],
                        default="OPE",
                        max_length=3,
                        verbose_name="Status",
                    ),
                ),
                ("data_inicio", models.DateTimeField(blank=True, null=True)),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                (
                    "pedido_editable",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "ucc_label",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="clientes.clientes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "finish",
                    models.ForeignKey(
                        blank=True,
                        default="-",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="_itens.finish",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="_itens.itemacabado",
                    ),
                ),
                (
                    "proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="pedidos.pedidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Pedido",
                "verbose_name_plural": "Itens Pedidos",
            },
        ),
    ]
