# Generated by Django 4.2.23 on 2025-07-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_itempedido_options_alter_pedidos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cargo_number',
            field=models.CharField(blank=True, default='--', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='lacre_number',
            field=models.CharField(blank=True, default='--', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedido_cliente',
            field=models.CharField(blank=True, default='--', max_length=50, null=True),
        ),
    ]
