# Generated by Django 4.2.23 on 2025-07-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedidos_cargo_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
