# Generated by Django 4.2.23 on 2025-07-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedidos_data_fim_pedidos_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
