# Generated by Django 4.2.23 on 2025-07-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedidos_data_fim_alter_pedidos_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='pedido_editable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
