# Generated by Django 4.2.23 on 2025-07-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedidos_pedido_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
