# Generated by Django 4.2.23 on 2025-07-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0025_item_qtde_volume'),
        ('pedidos', '0007_itempedido_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cad_item.finish'),
        ),
    ]
