# Generated by Django 4.2.23 on 2025-08-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_itempedido_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='ucc_label',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
