# Generated by Django 4.2.30 on 2026-04-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='ComponentesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Grupo Componentes',
                'verbose_name_plural': 'Grupos Componentes',
            },
        ),
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntde_pre', models.PositiveIntegerField(null=True)),
                ('qntde_usi', models.PositiveIntegerField(null=True)),
                ('qntde_lix', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer', models.CharField(max_length=20, unique=True, verbose_name='Código Família Comercial')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Família')),
            ],
            options={
                'verbose_name': 'Família Produto',
                'verbose_name_plural': 'Familia Produto',
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_finish', models.CharField(max_length=50, verbose_name='Código')),
                ('name_finish', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Acabamento',
                'verbose_name_plural': 'Acabamentos',
            },
        ),
        migrations.CreateModel(
            name='ItemAcabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_cod', models.CharField(max_length=20, unique=True)),
                ('item_desc', models.CharField(max_length=100, verbose_name='Nome Produto')),
                ('item_name', models.CharField(max_length=50, verbose_name='Nome Resumido')),
                ('qtd_per_day', models.IntegerField(verbose_name='Peças ao dia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qtde_volume', models.FloatField(blank=True, help_text='\n            Quantidade de volumes por item:\n            - 1 item = 1 volume: digite 1\n            - 1 item = 2 volumes: digite 2\n            - 2 itens = 1 volume: digite 0,5\n        ', null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itembase_cod', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('itembase_name', models.CharField(max_length=100, verbose_name='Nome Sub-Item')),
                ('ficha_tecnica', models.ImageField(blank=True, default='', upload_to='assets/ficha_tecnica/%Y%m/')),
                ('variation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Variação')),
                ('comprimento', models.FloatField(blank=True, null=True, verbose_name='Comprimento (mm)')),
                ('largura', models.FloatField(blank=True, null=True, verbose_name='Largura (mm)')),
                ('espessura', models.FloatField(blank=True, null=True, verbose_name='Espessura (mm)')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observações   ')),
                ('is_active', models.BooleanField(default=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_itens.componentes', verbose_name='Componente')),
            ],
            options={
                'verbose_name': 'Item Base',
                'verbose_name_plural': 'Itens Base',
            },
        ),
    ]
