# Generated by Django 4.2.24 on 2025-09-19 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('grupo', models.CharField(choices=[('Madeiras', 'Madeira'), ('Chapas', 'Chapas')], default='Madeiras', max_length=50)),
                ('unidade_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_resources.unidade_medida')),
            ],
        ),
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntde_pre', models.PositiveIntegerField(null=True)),
                ('qntde_usi', models.PositiveIntegerField(null=True)),
                ('qntde_lix', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer', models.CharField(max_length=20, unique=True, verbose_name='Código Família Comercial')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Família')),
            ],
            options={
                'verbose_name': 'Família Produto',
                'verbose_name_plural': 'Familia Produto',
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_finish', models.CharField(max_length=50, verbose_name='Código')),
                ('name_finish', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Acabamento',
                'verbose_name_plural': 'Acabamentos',
            },
        ),
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itembase_cod', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('itembase_name', models.CharField(max_length=100, verbose_name='Nome Sub-Item')),
                ('ficha_tecnica', models.ImageField(blank=True, default='', upload_to='assets/ficha_tecnica/%Y%m/')),
                ('variation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Variação')),
                ('comprimento', models.FloatField(blank=True, null=True, verbose_name='Comprimento (mm)')),
                ('largura', models.FloatField(blank=True, null=True, verbose_name='Largura (mm)')),
                ('espessura', models.FloatField(blank=True, null=True, verbose_name='Espessura (mm)')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observações   ')),
                ('is_active', models.BooleanField(default=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_itens.componentes', verbose_name='Componente')),
            ],
            options={
                'verbose_name': 'Sub-Item',
                'verbose_name_plural': 'Sub-Itens',
            },
        ),
        migrations.CreateModel(
            name='ItemAcabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_cod', models.CharField(max_length=20, unique=True)),
                ('item_desc', models.CharField(max_length=100, verbose_name='Nome Produto')),
                ('item_name', models.CharField(max_length=50, verbose_name='Nome Resumido')),
                ('qtd_per_day', models.IntegerField(verbose_name='Peças ao dia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qtde_volume', models.FloatField(blank=True, help_text='\n            Quantidade de volumes por item:\n            - 1 item = 1 volume: digite 1\n            - 1 item = 2 volumes: digite 2\n            - 2 itens = 1 volume: digite 0,5\n        ', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemacab_created_by', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_itens.familyprod', verbose_name='Família Produto')),
                ('subitens', models.ManyToManyField(related_name='subprodutos', through='_itens.Estrutura', to='_itens.itembase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemacab_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.AddField(
            model_name='estrutura',
            name='item_acab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_itens.itemacabado'),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='item_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_itens.itembase'),
        ),
        migrations.AlterUniqueTogether(
            name='estrutura',
            unique_together={('item_acab', 'item_base')},
        ),
    ]
