# Generated by Django 4.2.24 on 2025-09-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_itens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentes',
            old_name='nome',
            new_name='name',
        ),
    ]
