# Generated by Django 4.2.30 on 2026-04-08 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_itens', '0001_initial'),
        ('_resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemacabado',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemacab_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemacabado',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_itens.familyprod', verbose_name='Família Produto'),
        ),
        migrations.AddField(
            model_name='itemacabado',
            name='subitens',
            field=models.ManyToManyField(related_name='subprodutos', through='_itens.Estrutura', to='_itens.itembase'),
        ),
        migrations.AddField(
            model_name='itemacabado',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemacab_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='item_acab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_itens.itemacabado'),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='item_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_itens.itembase'),
        ),
        migrations.AddField(
            model_name='componentes',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_itens.componentesgroup'),
        ),
        migrations.AddField(
            model_name='componentes',
            name='unidade_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_resources.unidade_medida'),
        ),
        migrations.AlterUniqueTogether(
            name='estrutura',
            unique_together={('item_acab', 'item_base')},
        ),
    ]
