# Generated by Django 4.2.24 on 2025-09-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_itens', '0002_rename_nome_componentes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentesAdmin',
            fields=[
                ('componentes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='_itens.componentes')),
            ],
            bases=('_itens.componentes',),
        ),
        migrations.CreateModel(
            name='ComponentesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentesGroupAdmin',
            fields=[
                ('componentesgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='_itens.componentesgroup')),
            ],
            bases=('_itens.componentesgroup',),
        ),
        migrations.AlterField(
            model_name='componentes',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_itens.componentesgroup'),
        ),
    ]
