# Generated by Django 4.2.30 on 2026-04-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_itens', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estrutura',
            old_name='item_acab',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='estrutura',
            old_name='item_base',
            new_name='subitem',
        ),
        migrations.RenameField(
            model_name='familyprod',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='itemacabado',
            name='semi_code',
            field=models.CharField(blank=True, help_text='Digitar código sem ponto "."', max_length=50, null=True, verbose_name='Referência Semiacabado'),
        ),
        migrations.AlterUniqueTogether(
            name='estrutura',
            unique_together={('item', 'subitem')},
        ),
    ]
