# Generated by Django 4.2.30 on 2026-04-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_itens', '0003_rename_item_acab_estrutura_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes',
            name='prazo_entrega_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Dias necessários para recebimento do fornecedor', null=True, verbose_name='Prazo de Entrega (dias)'),
        ),
        migrations.AddField(
            model_name='componentes',
            name='qtde_minima',
            field=models.PositiveIntegerField(blank=True, help_text='Deixar em branco para compra sob demanda', null=True, verbose_name='Quantidade Mínima em Estoque'),
        ),
        migrations.AddField(
            model_name='componentes',
            name='tipo_compra',
            field=models.CharField(choices=[('estoque', 'Mantém em Estoque'), ('demanda', 'Compra sob Demanda')], default='demanda', max_length=10, verbose_name='Tipo de Compra'),
        ),
        migrations.CreateModel(
            name='ComponenteProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade por Unidade')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacoes', to='_itens.componentes')),
                ('item_acabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_comprados', to='_itens.itemacabado')),
            ],
            options={
                'verbose_name': 'Componente Programado',
                'verbose_name_plural': 'Componentes Programados',
                'unique_together': {('item_acabado', 'componente')},
            },
        ),
    ]
