# Generated by Django 4.2.30 on 2026-04-09 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_resources', '0001_initial'),
        ('_itens', '0004_componentes_prazo_entrega_dias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Grupo Insumo',
                'verbose_name_plural': 'Grupos Insumos',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código Insumo')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome/Descrição')),
                ('tipo', models.CharField(choices=[('madeira', 'Madeira'), ('tecido', 'Tecido'), ('espuma', 'Espuma'), ('hardware', 'Hardware'), ('pintura', 'Pintura/Acabamento'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Insumo')),
                ('especificacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificação (ex: 15mm, 1,5m, etc)')),
                ('estoque_minimo', models.FloatField(blank=True, help_text='Quantidade mínima para disparar reposição', null=True, verbose_name='Estoque Mínimo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_itens.insumogroup', verbose_name='Grupo')),
                ('unidade_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_resources.unidade_medida', verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='ComposicaoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name='Quantidade Necessária')),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes', to='_itens.insumo')),
                ('itembase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao_insumos', to='_itens.itembase')),
            ],
            options={
                'verbose_name': 'Composição de Insumo',
                'verbose_name_plural': 'Composições de Insumo',
                'unique_together': {('itembase', 'insumo')},
            },
        ),
        migrations.AddField(
            model_name='itembase',
            name='insumos',
            field=models.ManyToManyField(related_name='itemsbases', through='_itens.ComposicaoInsumo', to='_itens.insumo'),
        ),
    ]
