# Generated by Django 4.2.30 on 2026-04-08 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntde_pre', models.PositiveIntegerField(null=True)),
                ('qntde_usi', models.PositiveIntegerField(null=True)),
                ('qntde_lix', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer', models.CharField(max_length=20, unique=True, verbose_name='Código Família Comercial')),
                ('description', models.CharField(max_length=100, verbose_name='Nome Família')),
            ],
            options={
                'verbose_name': 'Família Produto',
                'verbose_name_plural': 'Familia Produto',
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_finish', models.CharField(max_length=50, verbose_name='Código')),
                ('name_finish', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Acabamento',
                'verbose_name_plural': 'Acabamentos',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=15, unique=True)),
                ('material_description', models.CharField(max_length=100)),
                ('material_group', models.CharField(choices=[('Madeiras', 'Madeira'), ('Chapas', 'Chapas')], default='Madeiras', max_length=50)),
                ('unidade_medida', models.CharField(choices=[('m³', 'Metros Cúbicos'), ('m²', 'Metros Quadrados'), ('ml', 'Metro Linear')], default='cm', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subitem_cod', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name_subitem', models.CharField(max_length=100, verbose_name='Nome Sub-Item')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observações   ')),
                ('ficha_tecnica', models.ImageField(blank=True, default='', upload_to='assets/ficha_tecnica/%Y%m/')),
                ('variation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Variação')),
                ('comprimento', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Comprimento (mm)')),
                ('largura', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Largura (mm)')),
                ('espessura', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Espessura (mm)')),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cad_item.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Sub-Item',
                'verbose_name_plural': 'Sub-Itens',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_cod', models.CharField(max_length=20, unique=True)),
                ('name_prod', models.CharField(max_length=100, verbose_name='Nome Produto')),
                ('name_abrev', models.CharField(max_length=50, verbose_name='Nome Resumido')),
                ('semi_code', models.CharField(help_text='Digitar código sem ponto "."', max_length=50, verbose_name='Referência Semiacabado')),
                ('qtd_per_day', models.IntegerField(verbose_name='Peças ao dia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qtde_volume', models.FloatField(blank=True, help_text='\n            Quantidade de volumes por item:\n            - 1 item = 1 volume: digite 1\n            - 1 item = 2 volumes: digite 2\n            - 2 itens = 1 volume: digite 0,5\n        ', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_created_by', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.familyprod', verbose_name='Família Produto')),
                ('subitens', models.ManyToManyField(related_name='subprodutos', through='cad_item.Estrutura', to='cad_item.subitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.AddField(
            model_name='estrutura',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.item'),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='subitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.subitem'),
        ),
        migrations.AlterUniqueTogether(
            name='estrutura',
            unique_together={('item', 'subitem')},
        ),
    ]
