# Generated by Django 5.1.1 on 2024-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProd',
            fields=[
                ('refer', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Família Produto',
                'verbose_name_plural': 'Familias Produto',
            },
        ),
    ]
