# Generated by Django 5.1.1 on 2024-09-27 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer', models.CharField(max_length=20, unique=True, verbose_name='Referência')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('description_resume', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição Resumida')),
                ('code_semiacabado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Semiacabado')),
                ('observation', models.TextField(verbose_name='Narrativa')),
                ('qtd_per_day', models.IntegerField(verbose_name='Peças ao dia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.familyprod', verbose_name='Família Produto')),
            ],
            options={
                'verbose_name': 'Cadastro Item',
                'verbose_name_plural': 'Cadastro Itens',
            },
        ),
    ]
