# Generated by Django 5.1.1 on 2024-09-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0002_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer', models.CharField(max_length=20, unique=True, verbose_name='Referência')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('observation', models.TextField(verbose_name='Narrativa')),
                ('ficha_tecnica', models.ImageField(blank=True, default='', null=True, upload_to='assets/ficha_tecnica/%Y%m/')),
                ('variation', models.CharField(max_length=50, null=True, verbose_name='Variação')),
                ('active', models.BooleanField(default=True)),
                ('refer_aux_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cad_item.produtos')),
            ],
            options={
                'verbose_name': 'Cadastro Sub-Produto',
                'verbose_name_plural': 'Cadastro Sub-Produtos',
            },
        ),
    ]
