# Generated by Django 5.1.1 on 2024-09-27 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0003_subprodutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Narrativa'),
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.produtos')),
                ('subproduto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.subprodutos')),
            ],
            options={
                'unique_together': {('produto', 'subproduto')},
            },
        ),
    ]
