# Generated by Django 5.1.1 on 2024-09-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0004_alter_produtos_observation_bom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='family',
        ),
        migrations.RemoveField(
            model_name='subprodutos',
            name='refer_aux_father',
        ),
        migrations.DeleteModel(
            name='BOM',
        ),
        migrations.DeleteModel(
            name='FamilyProd',
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
        migrations.DeleteModel(
            name='SubProdutos',
        ),
    ]
