# Generated by Django 4.1.13 on 2024-10-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cad_item', '0005_remove_produtos_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer', models.CharField(max_length=20, unique=True, verbose_name='Código Família Comercial')),
                ('description', models.CharField(max_length=100, verbose_name='Nome Família')),
            ],
            options={
                'verbose_name': 'Família Produto',
                'verbose_name_plural': 'Familia Produto',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_cod', models.CharField(max_length=20, unique=True, verbose_name='Referência')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Produto')),
                ('name_abrev', models.CharField(max_length=50, verbose_name='Nome Resumido')),
                ('semi_code', models.CharField(max_length=50, verbose_name='Referência Semiacabado')),
                ('qtd_per_day', models.IntegerField(verbose_name='Peças ao dia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.familyprod', verbose_name='Família Produto')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
