# Generated by Django 4.1.13 on 2024-10-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subitem_cod', models.CharField(max_length=20, unique=True, verbose_name='Referência')),
            ],
            options={
                'verbose_name': 'Sub-Item',
                'verbose_name_plural': 'Sub-Itens',
            },
        ),
    ]
