# Generated by Django 4.1.13 on 2024-10-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0007_subitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subitem',
            name='ficha_tecnica',
            field=models.ImageField(blank=True, default='', null=True, upload_to='assets/ficha_tecnica/%Y%m/'),
        ),
        migrations.AddField(
            model_name='subitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Sub-Item'),
        ),
        migrations.AddField(
            model_name='subitem',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Narrativa'),
        ),
        migrations.AddField(
            model_name='subitem',
            name='variation',
            field=models.CharField(max_length=50, null=True, verbose_name='Variação'),
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.item')),
                ('subitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.subitem')),
            ],
        ),
        migrations.AddField(
            model_name='subitem',
            name='code_father',
            field=models.ManyToManyField(related_name='code_semi_item', through='cad_item.FichaTecnica', to='cad_item.item'),
        ),
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.item')),
                ('subitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_item.subitem')),
            ],
            options={
                'unique_together': {('item', 'subitem')},
            },
        ),
    ]
