# Generated by Django 4.1.13 on 2024-10-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0008_subitem_ficha_tecnica_subitem_is_active_subitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome Sub-Item'),
        ),
    ]
