# Generated by Django 4.1.13 on 2024-10-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0009_alter_subitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='code_father',
        ),
    ]
