# Generated by Django 4.1.13 on 2024-10-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0010_remove_fichatecnica_quantidade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FichaTecnica',
        ),
    ]
