# Generated by Django 4.2.16 on 2024-10-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0012_item_created_at_item_created_by_item_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='ficha_tecnica',
            field=models.ImageField(blank=True, default='', upload_to='assets/ficha_tecnica/%Y%m/'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observações   '),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='subitem_cod',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
