# Generated by Django 4.2.16 on 2024-10-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0013_alter_subitem_ficha_tecnica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subitens',
            field=models.ManyToManyField(related_name='subprodutos', through='cad_item.Estrutura', to='cad_item.subitem'),
        ),
    ]
