# Generated by Django 4.2.16 on 2024-10-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0014_item_subitens'),
    ]

    operations = [
        migrations.CreateModel(
            name='TModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('for_inline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_test_models', to='cad_item.tmodel')),
                ('test', models.ManyToManyField(blank=True, related_name='related_test_models', to='cad_item.tmodel')),
            ],
        ),
    ]
