# Generated by Django 4.2.16 on 2024-10-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0015_tmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TModel',
        ),
    ]
