# Generated by Django 4.2.16 on 2024-11-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0016_delete_tmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='semi_code',
            field=models.CharField(help_text='Digitar código sem ponto "."', max_length=50, verbose_name='Referência Semiacabado'),
        ),
    ]
