# Generated by Django 4.2.16 on 2024-12-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0017_alter_item_semi_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estrutura',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='estrutura',
            name='qntde_lix',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='qntde_pre',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='qntde_usi',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
