# Generated by Django 4.2.22 on 2025-06-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0018_remove_estrutura_quantidade_estrutura_qntde_lix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=15, unique=True)),
                ('material_description', models.CharField(max_length=100)),
                ('material_group', models.CharField(choices=[('Madeiras', 'Madeira'), ('Chapas', 'Chapas')], default='Madeiras', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='subitem',
            name='espessura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subitem',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subitem',
            name='profundidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cad_item.material', verbose_name='Material'),
        ),
    ]
