# Generated by Django 4.2.22 on 2025-06-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0019_material_subitem_espessura_subitem_largura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unidade_medida',
            field=models.CharField(choices=[('m³', 'Metros Cúbicos'), ('m²', 'Metros Quadrados'), ('ml', 'Metro Linear')], default='cm', max_length=50),
        ),
    ]
