# Generated by Django 4.2.22 on 2025-06-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0020_material_unidade_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitem',
            name='profundidade',
        ),
        migrations.AddField(
            model_name='subitem',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comprimento (mm)'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='espessura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Espessura (mm)'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura (mm)'),
        ),
    ]
