# Generated by Django 4.2.23 on 2025-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0021_remove_subitem_profundidade_subitem_comprimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='name_prod',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='name',
            new_name='name_subitem',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_cod',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Comprimento (mm)'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='espessura',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Espessura (mm)'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Largura (mm)'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='variation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Variação'),
        ),
    ]
