# Generated by Django 4.2.23 on 2025-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0022_rename_name_item_name_prod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_finish', models.CharField(max_length=50, verbose_name='Código')),
                ('name_finish', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Acabamento',
                'verbose_name_plural': 'Acabamentos',
            },
        ),
        migrations.AlterModelOptions(
            name='familyprod',
            options={'verbose_name': ('Família Produto',), 'verbose_name_plural': ('Familia Produto',)},
        ),
    ]
