# Generated by Django 4.2.23 on 2025-07-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0023_finish_alter_familyprod_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyprod',
            options={'verbose_name': 'Família Produto', 'verbose_name_plural': 'Familia Produto'},
        ),
    ]
