# Generated by Django 4.2.23 on 2025-07-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0024_alter_familyprod_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qtde_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
