# Generated by Django 4.2.23 on 2025-08-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0025_item_qtde_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qtde_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
