# Generated by Django 4.2.23 on 2025-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0026_alter_item_qtde_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qtde_volume',
            field=models.FloatField(blank=True, help_text='\n            Quantidade de volumes por item:\n            - 1 item = 1 volume: digite 1\n            - 1 item = 2 volumes: digite 2\n            - 2 itens = 1 volume: digite 0,5\n        ', null=True),
        ),
    ]
