# Generated by Django 4.2.24 on 2025-09-19 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cad_item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Data Prevista Início')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Data Prevista Fim')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cad_item.item')),
            ],
            options={
                'verbose_name': 'Item Programado',
                'verbose_name_plural': 'Itens Programados',
            },
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Ordem Produção')),
                ('prog_year', models.CharField(blank=True, default='25', help_text='Digitar somente 2 dígitos do ano.', max_length=2, null=True, verbose_name='Ano da Programação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_updated_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Status Programação',
                'verbose_name_plural': 'Status Programações',
            },
        ),
        migrations.CreateModel(
            name='SubItemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_pre', models.PositiveIntegerField(blank=True, null=True)),
                ('qtde_usi', models.PositiveIntegerField(blank=True, null=True)),
                ('qtde_lix', models.PositiveIntegerField(blank=True, null=True)),
                ('produto_programado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppcp.itemprogramacao')),
                ('programacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppcp.manufacturingorder')),
                ('subproduto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cad_item.subitem')),
            ],
            options={
                'verbose_name': 'SubItem Programado',
                'verbose_name_plural': 'SubItens Programados',
            },
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppcp.statusorder'),
        ),
        migrations.AddField(
            model_name='itemprogramacao',
            name='programacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppcp.manufacturingorder'),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('local', models.CharField(max_length=50)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cad_item.item')),
            ],
        ),
    ]
