# Generated by Django 4.1.13 on 2024-10-02 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cad_item', '0012_item_created_at_item_created_by_item_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cad_item.item')),
            ],
            options={
                'verbose_name': 'Item Programado',
                'verbose_name_plural': 'Itens Programados',
            },
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ordem Produção')),
                ('prog_year', models.CharField(blank=True, default='24', help_text='digitar somente 2 dígitos do ano.', max_length=2, null=True, verbose_name='Ano da Programação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_updated_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Status Programação',
                'verbose_name_plural': 'Status Programações',
            },
        ),
        migrations.CreateModel(
            name='SubItemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cad_item.item')),
                ('produto_programado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppcp.itemprogramacao')),
                ('programacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppcp.manufacturingorder')),
                ('subproduto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cad_item.subitem')),
            ],
            options={
                'verbose_name': 'SubItem Programado',
                'verbose_name_plural': 'SubItens Programados',
            },
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppcp.statusorder'),
        ),
        migrations.AddField(
            model_name='itemprogramacao',
            name='programacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppcp.manufacturingorder'),
        ),
    ]
