# Generated by Django 4.2.16 on 2024-10-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Ordem Produção'),
        ),
    ]
