# Generated by Django 4.2.30 on 2026-04-08 22:21

from django.db import migrations, models
import ppcp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='prog_year',
            field=models.CharField(blank=True, default=ppcp.models.get_current_year, help_text='Digitar somente 2 dígitos do ano.', max_length=2, null=True, verbose_name='Ano da Programação'),
        ),
    ]
