# Generated by Django 4.2.16 on 2024-10-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0016_delete_tmodel'),
        ('ppcp', '0002_alter_manufacturingorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprogramacao',
            name='ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemprogramacao',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('local', models.CharField(max_length=50)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cad_item.item')),
            ],
        ),
    ]
