# Generated by Django 4.2.16 on 2024-10-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppcp', '0003_itemprogramacao_ends_at_itemprogramacao_start_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitemprogramacao',
            name='item',
        ),
    ]
