# Generated by Django 4.2.16 on 2024-11-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcp', '0004_remove_subitemprogramacao_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprogramacao',
            name='ends_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista Fim'),
        ),
        migrations.AlterField(
            model_name='itemprogramacao',
            name='start_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista Início'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='prog_year',
            field=models.CharField(blank=True, default='24', help_text='Digitar somente 2 dígitos do ano.', max_length=2, null=True, verbose_name='Ano da Programação'),
        ),
    ]
