# Generated by Django 4.2.16 on 2024-12-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcp', '0005_alter_itemprogramacao_ends_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitemprogramacao',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='subitemprogramacao',
            name='qtde_lix',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subitemprogramacao',
            name='qtde_pre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subitemprogramacao',
            name='qtde_usi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
