# Generated by Django 4.2.22 on 2025-06-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcp', '0006_remove_subitemprogramacao_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='prog_year',
            field=models.CharField(blank=True, default='25', help_text='Digitar somente 2 dígitos do ano.', max_length=2, null=True, verbose_name='Ano da Programação'),
        ),
    ]
