# Generated by Django 4.2.30 on 2026-04-08 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apont_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apont_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Apontamento',
                'verbose_name_plural': 'Tipo Apontamentos',
            },
        ),
        migrations.CreateModel(
            name='Motive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Motivo Retrabalho',
                'verbose_name_plural': 'Motivo Retrabalhos',
            },
        ),
        migrations.CreateModel(
            name='StopsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria Parada',
                'verbose_name_plural': 'Categorias Paradas',
            },
        ),
        migrations.CreateModel(
            name='StopsMotive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apont.stopscategory')),
            ],
            options={
                'verbose_name': 'Subcategoria Parada',
                'verbose_name_plural': 'Subcategorias Paradas',
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.machines')),
                ('motive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.stopsmotive')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
