# Generated by Django 4.1.13 on 2024-09-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apont_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apont_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pre_f_015',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('programacao', models.CharField(max_length=100)),
                ('produto_pai', models.CharField(max_length=100)),
                ('produto_apontado', models.CharField(max_length=100)),
                ('hora_inicio_setup', models.TimeField()),
                ('hora_inicio_producao', models.TimeField()),
                ('hora_final_producao', models.TimeField()),
                ('qtde_boa', models.IntegerField()),
                ('refugo', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pre_f_016',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('programacao', models.CharField(max_length=100)),
                ('produto_pai', models.CharField(max_length=100)),
                ('produto_apontado', models.CharField(max_length=100)),
                ('hora_inicio_setup', models.TimeField()),
                ('hora_inicio_producao', models.TimeField()),
                ('hora_final_producao', models.TimeField()),
                ('qtde_boa', models.IntegerField()),
                ('refugo', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pre_f_017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('programacao', models.CharField(max_length=100)),
                ('produto_pai', models.CharField(max_length=100)),
                ('produto_apontado', models.CharField(max_length=100)),
                ('hora_inicio_setup', models.TimeField()),
                ('hora_inicio_producao', models.TimeField()),
                ('hora_final_producao', models.TimeField()),
                ('qtde_boa', models.IntegerField()),
                ('refugo', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usi_f_020',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('programacao', models.CharField(max_length=100)),
                ('produto_pai', models.CharField(max_length=100)),
                ('produto_apontado', models.CharField(max_length=100)),
                ('hora_inicio_setup', models.TimeField()),
                ('hora_inicio_producao', models.TimeField()),
                ('hora_final_producao', models.TimeField()),
                ('qtde_boa', models.IntegerField()),
                ('refugo', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usi_f_21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('programacao', models.CharField(max_length=100)),
                ('produto_pai', models.CharField(max_length=100)),
                ('produto_apontado', models.CharField(max_length=100)),
                ('hora_inicio_setup', models.TimeField()),
                ('hora_inicio_producao', models.TimeField()),
                ('hora_final_producao', models.TimeField()),
                ('qtde_boa', models.IntegerField()),
                ('refugo', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
