# Generated by Django 4.2.30 on 2026-04-09 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppcp', '0002_alter_manufacturingorder_prog_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule', '0001_initial'),
        ('apont', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stops',
            options={'ordering': ['-date'], 'verbose_name': 'Parada de Produção', 'verbose_name_plural': 'Paradas de Produção'},
        ),
        migrations.AlterField(
            model_name='stops',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rule.machines'),
        ),
        migrations.CreateModel(
            name='RegistroApontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Apontamento')),
                ('hora_inicio_setup', models.TimeField(blank=True, null=True, verbose_name='Hora Início Setup')),
                ('hora_fim_setup', models.TimeField(blank=True, null=True, verbose_name='Hora Fim Setup')),
                ('hora_inicio_producao', models.TimeField(blank=True, null=True, verbose_name='Hora Início Produção')),
                ('hora_fim_producao', models.TimeField(blank=True, null=True, verbose_name='Hora Fim Produção')),
                ('qtde_programada', models.IntegerField(default=0, verbose_name='Quantidade Programada')),
                ('qtde_produzida_boa', models.IntegerField(default=0, verbose_name='Quantidade Produzida (Boa)')),
                ('qtde_refugo', models.IntegerField(default=0, verbose_name='Quantidade Refugo')),
                ('qtde_retrabalho', models.IntegerField(default=0, verbose_name='Quantidade Retrabalho')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='rule.machines')),
                ('motivo_retrabalho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.motive', verbose_name='Motivo do Retrabalho')),
                ('programacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppcp.itemprogramacao', verbose_name='Ordem de Produção')),
                ('subproduto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppcp.subitemprogramacao', verbose_name='SubItem/Componente')),
                ('tipo_apontamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type', verbose_name='Tipo de Apontamento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Apontamento de Produção',
                'verbose_name_plural': 'Apontamentos de Produção',
                'ordering': ['-data'],
                'unique_together': {('machine', 'data', 'hora_inicio_producao')},
            },
        ),
    ]
