# Generated by Django 4.1.13 on 2024-09-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apont', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usi_f_21',
            new_name='Usi_f_021',
        ),
    ]
