# Generated by Django 4.1.13 on 2024-09-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apont', '0002_rename_usi_f_21_usi_f_021'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_f_015',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.motive'),
        ),
        migrations.AddField(
            model_name='pre_f_015',
            name='tipo_apontamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AddField(
            model_name='pre_f_016',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.motive'),
        ),
        migrations.AddField(
            model_name='pre_f_016',
            name='tipo_apontamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AddField(
            model_name='pre_f_017',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.motive'),
        ),
        migrations.AddField(
            model_name='pre_f_017',
            name='tipo_apontamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AddField(
            model_name='usi_f_020',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.motive'),
        ),
        migrations.AddField(
            model_name='usi_f_020',
            name='tipo_apontamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AddField(
            model_name='usi_f_021',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.motive'),
        ),
        migrations.AddField(
            model_name='usi_f_021',
            name='tipo_apontamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
    ]
