# Generated by Django 4.1.13 on 2024-09-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apont', '0003_pre_f_015_motivo_pre_f_015_tipo_apontamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_f_015',
            name='tipo_apontamento',
            field=models.ForeignKey(default='Producao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='tipo_apontamento',
            field=models.ForeignKey(default='Producao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='tipo_apontamento',
            field=models.ForeignKey(default='Producao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='tipo_apontamento',
            field=models.ForeignKey(default='Producao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='tipo_apontamento',
            field=models.ForeignKey(default='Producao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
    ]
