# Generated by Django 4.2.16 on 2024-11-08 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apont', '0006_stopscategory_pre_f_015_user_pre_f_016_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usi_f_004',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('programacao', models.CharField(max_length=100)),
                ('produto_pai', models.CharField(max_length=100)),
                ('produto_apontado', models.CharField(max_length=100)),
                ('hora_inicio_setup', models.TimeField()),
                ('hora_inicio_producao', models.TimeField()),
                ('hora_final_producao', models.TimeField()),
                ('qtde_boa', models.IntegerField()),
                ('refugo', models.IntegerField()),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.motive')),
                ('tipo_apontamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
