# Generated by Django 4.2.16 on 2024-11-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apont', '0007_usi_f_004'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_f_015',
            name='ano',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pre_f_016',
            name='ano',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pre_f_017',
            name='ano',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='usi_f_004',
            name='ano',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='usi_f_020',
            name='ano',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='usi_f_021',
            name='ano',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='pre_f_015',
            name='hora_final_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_015',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_015',
            name='qtde_boa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_015',
            name='refugo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_015',
            name='tipo_apontamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='hora_final_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='qtde_boa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='refugo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='tipo_apontamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='hora_final_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='qtde_boa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='refugo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='tipo_apontamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='hora_final_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='qtde_boa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='refugo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='tipo_apontamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='hora_final_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='qtde_boa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='refugo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='tipo_apontamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='hora_final_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='qtde_boa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='refugo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='tipo_apontamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apont.apont_type'),
        ),
    ]
