# Generated by Django 4.2.16 on 2024-11-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_item', '0017_alter_item_semi_code'),
        ('apont', '0008_pre_f_015_ano_pre_f_016_ano_pre_f_017_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_f_015',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cad_item.item'),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cad_item.item'),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cad_item.item'),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cad_item.item'),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cad_item.item'),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cad_item.item'),
        ),
    ]
