# Generated by Django 4.2.16 on 2024-11-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppcp', '0005_alter_itemprogramacao_ends_at_and_more'),
        ('apont', '0010_alter_pre_f_015_produto_apontado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_f_015',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppcp.itemprogramacao'),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppcp.itemprogramacao'),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppcp.itemprogramacao'),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppcp.itemprogramacao'),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppcp.itemprogramacao'),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppcp.itemprogramacao'),
        ),
    ]
