# Generated by Django 4.2.16 on 2024-11-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apont', '0011_alter_pre_f_015_produto_pai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_f_015',
            name='hora_final_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_015',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_015',
            name='qtde_boa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_015',
            name='refugo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='hora_final_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='qtde_boa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_016',
            name='refugo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='hora_final_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='qtde_boa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pre_f_017',
            name='refugo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='hora_final_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='qtde_boa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_004',
            name='refugo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='hora_final_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='qtde_boa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_020',
            name='refugo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='hora_final_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='hora_inicio_producao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='qtde_boa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usi_f_021',
            name='refugo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
