# Generated by Django 4.2.16 on 2024-11-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apont', '0012_alter_pre_f_015_hora_final_producao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_f_015',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AddField(
            model_name='pre_f_016',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AddField(
            model_name='pre_f_017',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AddField(
            model_name='usi_f_004',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AddField(
            model_name='usi_f_020',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AddField(
            model_name='usi_f_021',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
    ]
