# Generated by Django 4.2.16 on 2024-12-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apont', '0013_pre_f_015_status_pre_f_016_status_pre_f_017_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apont_type',
            options={'verbose_name': 'Tipo Apontamento', 'verbose_name_plural': 'Tipo Apontamentos'},
        ),
        migrations.AlterModelOptions(
            name='motive',
            options={'verbose_name': 'Motivo Retrabalho', 'verbose_name_plural': 'Motivo Retrabalhos'},
        ),
        migrations.AlterModelOptions(
            name='stopscategory',
            options={'verbose_name': 'Categoria Parada', 'verbose_name_plural': 'Categorias Paradas'},
        ),
        migrations.AlterModelOptions(
            name='stopsmotive',
            options={'verbose_name': 'Subcategoria Parada', 'verbose_name_plural': 'Subcategorias Paradas'},
        ),
    ]
