# Generated by Django 4.2.23 on 2025-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('razao_social', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nome_fantasia', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
                ('market', models.CharField(choices=[('M.I.', 'Mercado Interno'), ('M.E.', 'Mercado Externo')], default='M.I.', max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
