# Generated by Django 4.2.23 on 2025-07-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cad_item', '0023_finish_alter_familyprod_options'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_number', models.CharField(max_length=50, unique=True)),
                ('container_number', models.CharField(max_length=50)),
                ('lacre_number', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes')),
            ],
            options={
                'verbose_name': ('Proforma',),
                'verbose_name_plural': ('Proformas',),
            },
        ),
        migrations.CreateModel(
            name='ItemProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cad_item.finish')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cad_item.item')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carregamento.proformas')),
            ],
            options={
                'verbose_name': 'Item Proforma',
                'verbose_name_plural': 'Itens Proforma',
            },
        ),
        migrations.CreateModel(
            name='Carregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_carregada', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carregamento.itemproforma')),
                ('proforma_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carregamento.proformas')),
            ],
            options={
                'verbose_name': 'Carregamento',
                'verbose_name_plural': 'Carregamentos',
            },
        ),
    ]
