# Generated by Django 4.2.30 on 2026-04-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('qtde_carregada', models.FloatField(blank=True, default=0, null=True)),
                ('operador', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.itempedido')),
                ('pedido_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.pedidos')),
            ],
            options={
                'verbose_name': 'Carregamento',
                'verbose_name_plural': 'Carregamentos',
            },
        ),
        migrations.CreateModel(
            name='BarcodeProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_completo', models.CharField(max_length=100, unique=True)),
                ('data_processado', models.DateTimeField(auto_now_add=True)),
                ('carregamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processsed_barcodes', to='carregamento.carregamento')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.itempedido')),
            ],
            options={
                'verbose_name': 'Código Processado',
                'verbose_name_plural': 'Códigos Processados',
                'ordering': ['-data_processado'],
                'indexes': [models.Index(fields=['item'], name='carregament_item_id_ea09e2_idx'), models.Index(fields=['carregamento'], name='carregament_carrega_99cacc_idx')],
            },
        ),
    ]
