# Generated by Django 4.2.23 on 2025-07-14 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carregamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamento',
            name='data_fim',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carregamento',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
