# Generated by Django 4.2.23 on 2025-07-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carregamento', '0002_carregamento_data_fim_carregamento_data_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proformas',
            options={'verbose_name': 'Proforma', 'verbose_name_plural': 'Proformas'},
        ),
    ]
