# Generated by Django 4.2.23 on 2025-07-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamento', '0003_alter_proformas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformas',
            name='container_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proformas',
            name='lacre_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
