# Generated by Django 4.2.23 on 2025-07-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamento', '0004_alter_proformas_container_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformas',
            name='status',
            field=models.CharField(choices=[('OPE', 'Aberto'), ('LOD', 'Carregando'), ('CAN', 'Cancelado'), ('FIN', 'Concluído')], default='OPE', max_length=3, verbose_name='Status'),
        ),
    ]
