# Generated by Django 4.2.23 on 2025-07-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carregamento', '0005_proformas_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproforma',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='itemproforma',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemproforma',
            name='proforma',
        ),
        migrations.RemoveField(
            model_name='proformas',
            name='cliente',
        ),
    ]
