# Generated by Django 4.2.23 on 2025-07-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('carregamento', '0006_remove_itemproforma_finish_remove_itemproforma_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregamento',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.itempedido'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='proforma_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.pedidos'),
        ),
        migrations.DeleteModel(
            name='ItemProforma',
        ),
        migrations.DeleteModel(
            name='Proformas',
        ),
    ]
