# Generated by Django 4.2.23 on 2025-07-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamento', '0007_alter_carregamento_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carregamento',
            old_name='proforma_data',
            new_name='pedido_data',
        ),
        migrations.AddField(
            model_name='carregamento',
            name='operador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
