# Generated by Django 4.2.23 on 2025-07-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamento', '0008_rename_proforma_data_carregamento_pedido_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_completo', models.CharField(max_length=100, unique=True)),
                ('data_processado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código Processado',
                'verbose_name_plural': 'Códigos Processados',
                'ordering': ['-data_processado'],
            },
        ),
    ]
