# Generated by Django 4.2.23 on 2025-07-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_itempedido_finish'),
        ('carregamento', '0009_barcodeprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodeprocessed',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.itempedido'),
        ),
    ]
