# Generated by Django 4.2.23 on 2025-07-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_itempedido_finish'),
        ('carregamento', '0010_barcodeprocessed_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodeprocessed',
            name='carregamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processsed_barcodes', to='carregamento.carregamento'),
        ),
        migrations.AlterField(
            model_name='barcodeprocessed',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.itempedido'),
        ),
        migrations.AddIndex(
            model_name='barcodeprocessed',
            index=models.Index(fields=['item'], name='carregament_item_id_ea09e2_idx'),
        ),
        migrations.AddIndex(
            model_name='barcodeprocessed',
            index=models.Index(fields=['carregamento'], name='carregament_carrega_99cacc_idx'),
        ),
    ]
