# Generated by Django 4.2.23 on 2025-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamento', '0011_barcodeprocessed_carregamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregamento',
            name='qtde_carregada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
