# Generated by Django 4.2.23 on 2025-08-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamento', '0012_alter_carregamento_qtde_carregada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregamento',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
