# Generated by Django 4.2.23 on 2025-08-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregamento', '0013_alter_carregamento_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregamento',
            name='qtde_carregada',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
