# Generated by Django 4.1.13 on 2024-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_f_015',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('oee_indice', models.FloatField()),
                ('availability', models.FloatField()),
                ('performance', models.FloatField()),
                ('quality', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pre_f_016',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('oee_indice', models.FloatField()),
                ('availability', models.FloatField()),
                ('performance', models.FloatField()),
                ('quality', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pre_f_017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('oee_indice', models.FloatField()),
                ('availability', models.FloatField()),
                ('performance', models.FloatField()),
                ('quality', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usi_f_020',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('oee_indice', models.FloatField()),
                ('availability', models.FloatField()),
                ('performance', models.FloatField()),
                ('quality', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usi_f_021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('oee_indice', models.FloatField()),
                ('availability', models.FloatField()),
                ('performance', models.FloatField()),
                ('quality', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
