# Generated by Django 4.2.30 on 2026-04-09 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
        ('desempenho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('disponibilidade', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disponibilidade (%)')),
                ('performance', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Performance (%)')),
                ('qualidade', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Qualidade (%)')),
                ('oee', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='OEE (%)')),
                ('tempo_total_disponivel_minutos', models.FloatField(default=0, verbose_name='Tempo Total Disponível (min)')),
                ('tempo_parado_minutos', models.FloatField(default=0, verbose_name='Tempo Parado (min)')),
                ('tempo_producao_minutos', models.FloatField(default=0, verbose_name='Tempo Produção (min)')),
                ('qtde_programada', models.IntegerField(default=0, verbose_name='Quantidade Programada')),
                ('qtde_produzida', models.IntegerField(default=0, verbose_name='Quantidade Produzida')),
                ('qtde_refugo', models.IntegerField(default=0, verbose_name='Quantidade Refugo')),
                ('qtde_retrabalho', models.IntegerField(default=0, verbose_name='Quantidade Retrabalho')),
                ('calculado_em', models.DateTimeField(auto_now=True, verbose_name='Calculado em')),
                ('calculado_por', models.CharField(default='sistema', max_length=100, verbose_name='Calculado por')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_desempenho', to='rule.machines', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Indicador de Desempenho',
                'verbose_name_plural': 'Indicadores de Desempenho',
                'ordering': ['-data', 'machine'],
                'unique_together': {('machine', 'data')},
            },
        ),
        migrations.CreateModel(
            name='ResumoDesempenhoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('disponibilidade_media', models.FloatField(default=0, verbose_name='Disponibilidade Média (%)')),
                ('performance_media', models.FloatField(default=0, verbose_name='Performance Média (%)')),
                ('qualidade_media', models.FloatField(default=0, verbose_name='Qualidade Média (%)')),
                ('oee_media', models.FloatField(default=0, verbose_name='OEE Média (%)')),
                ('qtde_maquinas', models.IntegerField(default=0, verbose_name='Qty Máquinas')),
                ('qtde_setores', models.IntegerField(default=0, verbose_name='Qty Setores')),
                ('qtde_produzida_total', models.IntegerField(default=0, verbose_name='Qtde Produzida Total')),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_desempenho', to='rule.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Resumo Grupo',
                'verbose_name_plural': 'Resumos Grupo',
                'ordering': ['-data', 'grupo'],
                'unique_together': {('grupo', 'data')},
            },
        ),
        migrations.CreateModel(
            name='ResumoDesempenhoSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('disponibilidade_media', models.FloatField(default=0, verbose_name='Disponibilidade Média (%)')),
                ('performance_media', models.FloatField(default=0, verbose_name='Performance Média (%)')),
                ('qualidade_media', models.FloatField(default=0, verbose_name='Qualidade Média (%)')),
                ('oee_media', models.FloatField(default=0, verbose_name='OEE Média (%)')),
                ('qtde_maquinas', models.IntegerField(default=0, verbose_name='Qty Máquinas')),
                ('qtde_programada_total', models.IntegerField(default=0, verbose_name='Qtde Programada Total')),
                ('qtde_produzida_total', models.IntegerField(default=0, verbose_name='Qtde Produzida Total')),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_desempenho', to='rule.sectors', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Resumo Setor',
                'verbose_name_plural': 'Resumos Setor',
                'ordering': ['-data', 'setor'],
                'unique_together': {('setor', 'data')},
            },
        ),
        migrations.DeleteModel(
            name='Pre_f_015',
        ),
        migrations.DeleteModel(
            name='Pre_f_016',
        ),
        migrations.DeleteModel(
            name='Pre_f_017',
        ),
        migrations.DeleteModel(
            name='Usi_f_020',
        ),
        migrations.DeleteModel(
            name='Usi_f_021',
        ),
    ]
