# Generated by Django 4.1.13 on 2024-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_menulink_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(default='', upload_to='assets/favicon/%Y%m/'),
        ),
    ]
