# Generated by Django 4.1.13 on 2024-09-30 18:30

from django.db import migrations, models
import django.db.models.deletion
import utils.model_validator


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_sitesetup_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='logo_site',
            field=models.ImageField(default='', upload_to='assets/Logo/%Y%m/'),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='site_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='site_setup.sitesetup'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/', validators=[utils.model_validator.validate_png]),
        ),
    ]
