# Generated by Django 4.1.13 on 2024-10-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0007_sitesetup_logo_site_alter_menulink_site_setup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulink',
            old_name='level',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='menulink',
            name='site_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_setup.sitesetup'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='logo_site',
            field=models.ImageField(default='', upload_to='assets/Logo/%Y/%m/'),
        ),
    ]
