# Generated by Django 4.2.24 on 2025-09-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
        ('_operadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.workstation'),
        ),
    ]
