# Generated by Django 4.2.30 on 2026-04-08 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rule', '0001_initial'),
        ('_itens', '0001_initial'),
        ('_resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_created_by', to=settings.AUTH_USER_MODEL)),
                ('motivo_parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_resources.motivoretrabalho')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_updated_by', to=settings.AUTH_USER_MODEL)),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.workstation')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
            },
        ),
        migrations.CreateModel(
            name='Apontamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qtde_boa', models.FloatField(default=0)),
                ('qtde_refugo', models.FloatField(default=0)),
                ('datetime_start', models.DateTimeField(blank=True, null=True)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('tempo_hr', models.FloatField(default=0)),
                ('tempo_seg', models.FloatField(default=0)),
                ('code_read', models.CharField(blank=True, max_length=100, null=True)),
                ('programacao_ppcp', models.CharField(blank=True, max_length=100, null=True)),
                ('programacao_comercial', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('afeta_oee', models.BooleanField(default=True)),
                ('show_relatorio', models.BooleanField(default=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apont_created_by', to=settings.AUTH_USER_MODEL)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apont_operador', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_itens.itemacabado')),
                ('tipo_apontamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_resources.aponttype')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apont_updated_by', to=settings.AUTH_USER_MODEL)),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.workstation')),
            ],
            options={
                'verbose_name': 'Apontamento',
                'verbose_name_plural': 'Apontamentos',
            },
        ),
    ]
