# Generated by Django 4.2.24 on 2025-09-19 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_resources', '0001_initial'),
        ('_itens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule', '0001_initial'),
        ('_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apontamentos',
            options={'verbose_name': 'Apontamento', 'verbose_name_plural': 'Apontamentos'},
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='afeta_oee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='code_read',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apont_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='datetime_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apont_operador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_itens.itemacabado'),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='programacao_comercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='programacao_ppcp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='qtde_boa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='qtde_refugo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='show_relatorio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='tempo_hr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='tempo_seg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='tipo_apontamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_resources.aponttype'),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='apontamentos',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apont_updated_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apontamentos',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.workstation'),
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_created_by', to=settings.AUTH_USER_MODEL)),
                ('motivo_parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_resources.motivoretrabalho')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_updated_by', to=settings.AUTH_USER_MODEL)),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.workstation')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
            },
        ),
    ]
